name: openmmqmmm
#Only conda-forge allowed for now
channels:
  - conda-forge
#Packages for the ORCA+OpenMM QM/MM distribution of ASH
dependencies:
  - python=3.11
  - pip
  - openmm
  - pdbfixer
  - mdtraj
  - numpy
  - typing_extensions
  - pip:
      - geometric
#Optional extras (uncomment as needed):
#  - openbabel
#  - matplotlib
#  - scipy
#  - parmed
#  - openmm-plumed
